## defaults for _all_ profiles
[profile.default]
src = 'contracts'
libs = ["lib"]
out = 'out'
remappings = [
  '@openzeppelin/=node_modules/@openzeppelin/',
  '@chainlink=node_modules/@chainlink',
  'hardhat=node_modules/hardhat',
]
