## defaults for _all_ profiles
[profile.default]
src = 'contracts'
test = 'test'
libs = ["lib"]
out = 'out'
remappings = [
  '@openzeppelin/=node_modules/@openzeppelin/',
  '@chainlink=node_modules/@chainlink',
  'hardhat=node_modules/hardhat',
]
#libraries = []
#cache = true
#force = false
#evm_version = 'london'
gas_reports = [
  'GEMS',
  'LongShort*',
  'SytheticTokenMarketUpgradable',
  'OracleManagerFixedEpoch',
  'MarketTieredLeverage*',
]
### Sets the concrete solc version to use, this overrides the `auto_detect_solc` value
# solc_version = '0.8.15'
#auto_detect_solc = true
#offline = false
optimizer = true
optimizer_runs = 10000 # most of the functions in our dapp will be called more than 1000 times!
#verbosity = 0
#ignored_error_codes = []
fuzz_runs = 20 # less fuzzing locally
#ffi = false
#sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
#tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
#initial_balance = '0xffffffffffffffffffffffff'
block_number = 100000
#gas_limit = 9223372036854775807
#gas_price = 0
#block_base_fee_per_gas = 0
#block_coinbase = '0x0000000000000000000000000000000000000000'
block_timestamp = 1600000000
#block_difficulty = 0
#via_ir = false

[profile.ci]
fuzz-runs = 1_000                 # more fuzzing in pipeline
fuzz_max_global_rejects = 100_000 # Required until this is implemented: https://github.com/foundry-rs/foundry/issues/1202#issuecomment-1098556706

# ## NOTE: the below configuration isn't woring properly yet. Needs some work.
# #        https://docs.soliditylang.org/en/latest/smtchecker.html
# [ci.model_checker]
# contracts = { 'contracts/market/template/MarketTieredLeverage.sol' = [
#   'MarketTieredLeverage',
# ] }
# engine = 'chc' # or 'all'/'bmc'
# timeout = 10000
# targets = [
#   'assert',
#   'divByZero',
#   'underflow',
#   'overflow',
#   'divByZero',
#   'constantCondition',
#   'popEmptyArray',
#   'outOfBounds',
# ] # not included: 'balance'
